# Generated by Django 3.1.7 on 2021-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotConfigModel',
            fields=[
                ('id', models.AutoField(help_text='自增id', primary_key=True, serialize=False)),
                ('next_buy_price', models.DecimalField(decimal_places=8, help_text='下次开仓价(你下一仓位买入价)', max_digits=16, verbose_name='下次开仓价')),
                ('grid_sell_price', models.DecimalField(decimal_places=8, help_text='当前止盈价(你的当前仓位卖出价)', max_digits=16, verbose_name='当前止盈价')),
                ('step', models.IntegerField(help_text='当前仓位(0:仓位为空)', verbose_name='当前仓位')),
                ('profit_ratio', models.DecimalField(decimal_places=3, help_text='止盈比率(卖出价调整比率。如：设置为5,即为5%，当前买入价为100，那么下次卖出价为105)', max_digits=4, verbose_name='止盈比率')),
                ('double_throw_ratio', models.DecimalField(decimal_places=3, help_text='补仓比率(买入价调整比率。如：设置为5,即为5%当前买入价为100，那么下次买入价为95)', max_digits=4, verbose_name='补仓比率')),
                ('coin_type', models.CharField(help_text='交易对(你要进行交易的交易对，请参考币安现货。如：BTC 填入 BTCUSDT)', max_length=16, verbose_name='交易对')),
                ('quantity', models.CharField(help_text='交易数量(第一手买入1,第二手买入2...超过第三手以后的仓位均按照最后一位数量(3)买入),例如:1,2,3', max_length=256, verbose_name='交易数量')),
                ('max_count', models.IntegerField(help_text='连续买入而不卖出的最大次数', verbose_name='连续买入而不卖出的最大次数')),
                ('min_num', models.IntegerField(help_text='交易金额最小位数长度,如0.00001,则填入5', verbose_name='交易金额最小位数长度')),
                ('current_num', models.IntegerField(default=0, help_text='当前连续买入次数', verbose_name='当前连续买入次数')),
                ('current_income', models.DecimalField(decimal_places=6, default=0, help_text='当前收益', max_digits=10, verbose_name='当前收益')),
                ('if_use', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
        ),
    ]
